name: Build and publish to PyPI

on:
  push:
    branches:
      - "ci/use-trusted-publisher"
    tags:
      - "*"

jobs:
  build_and_publish:
    name: Build and publish
    runs-on: ubuntu-latest
    environment: testpypi
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - name: Checkout ğŸ”
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1

      - name: Set up Python ğŸ
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 #v4.7.1
        with:
          python-version: "3.9"

      - name: Install Poetry and pre-commit ğŸ’ˆ
        run: pip install poetry pre-commit

      - name: Install dependencies ğŸ› 
        run: poetry install

      #      - name: Run pre-commit ğŸ¤”
      #        run: pre-commit run --all-files
      #
      #      - name: Run tests ğŸŒˆ
      #        run: poetry run invoke test

      - name: Build the package ğŸ“¦
        run: poetry build

      - name: Publish package to PyPI ğŸ™Œ
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
#      - name: Publish package to PyPI ğŸ™Œ
#        run: |
#          set -e
#          poetry config http-basic.pypi "__token__" "${PYPI_TOKEN}"
#          poetry publish --build
#        env:
#          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
